"""The words the game can pick from."""

WORDS = [
    "adult",
    "advice",
    "arrangement",
    "attempt",
    "august",
    "autumn",
    "battery",
    "border",
    "brazil",
    "bread",
    "breeze",
    "brick",
    "browser",
    "butter",
    "calm",
    "camel",
    "canada",
    "canal",
    "casey",
    "cast",
    "cheese",
    "chose",
    "chutney",
    "claws",
    "coach",
    "compiler",
    "constantly",
    "contrast",
    "cookies",
    "cres",
    "customs",
    "damage",
    "danny",
    "database",
    "deeply",
    "depth",
    "desert",
    "discussion",
    "doll",
    "dolphin",
    "donkey",
    "dumpling",
    "egypt",
    "ellen",
    "essential",
    "exchange",
    "exist",
    "explanation",
    "facing",
    "falcon",
    "film",
    "finest",
    "fireplace",
    "floating",
    "folks",
    "forest",
    "fort",
    "garage",
    "glacier",
    "grabbed",
    "grandmother",
    "habit",
    "happily",
    "harry",
    "heading",
    "homework",
    "hunter",
    "iceland",
    "illinois",
    "image",
    "independent",
    "instant",
    "internet",
    "january",
    "kentucky",
    "keyboard",
    "kids",
    "label",
    "lee",
    "lentils",
    "library",
    "lungs",
    "manufacturing",
    "martin",
    "mathematics",
    "meadow",
    "melted",
    "memory",
    "mill",
    "mission",
    "monitor",
    "monkey",
    "mount",
    "mysterious",
    "neighborhood",
    "nepal",
    "network",
    "noodles",
    "norway",
    "nuts",
    "occasionally",
    "official",
    "orange",
    "ourselves",
    "palace",
    "pennsylvania",
    "pepper",
    "philadelphia",
    "plates",
    "poetry",
    "policeman",
    "positive",
    "possibly",
    "practical",
    "pride",
    "program",
    "promised",
    "rabbit",
    "recall",
    "relationship",
    "remarkable",
    "require",
    "rhyme",
    "rocky",
    "rubbed",
    "rush",
    "sale",
    "satellites",
    "satisfied",
    "scared",
    "science",
    "selection",
    "shake",
    "shaking",
    "shallow",
    "shout",
    "silly",
    "simplest",
    "slight",
    "slip",
    "slope",
    "soap",
    "software",
    "solar",
    "species",
    "spin",
    "stiff",
    "student",
    "swung",
    "tales",
    "teacher",
    "thumb",
    "thunder",
    "tobacco",
    "toy",
    "trap",
    "treated",
    "tune",
    "turtle",
    "university",
    "vapor",
    "vessels",
    "wealth",
    "wolf",
    "zoo",
]


CATEGORIES = {
    "animals": [
        "donkey",
        "monkey",
        "wolf",
        "species",
        "hunter",
        "rabbit",
        "turtle",
        "falcon",
        "camel",
        "dolphin",
    ],
    "places": [
        "egypt",
        "norway",
        "illinois",
        "pennsylvania",
        "philadelphia",
        "nepal",
        "canada",
        "brazil",
        "iceland",
        "kentucky",
    ],
    "nature": [
        "autumn",
        "breeze",
        "solar",
        "canal",
        "mount",
        "forest",
        "glacier",
        "meadow",
        "thunder",
        "desert",
    ],
    "school": [
        "mathematics",
        "university",
        "poetry",
        "selection",
        "discussion",
        "science",
        "library",
        "teacher",
        "student",
        "homework",
    ],
    "technology": [
        "keyboard",
        "internet",
        "monitor",
        "program",
        "network",
        "battery",
        "browser",
        "database",
        "compiler",
        "software",
    ],
    "food": [
        "cookies",
        "bread",
        "butter",
        "noodles",
        "dumpling",
        "cheese",
        "orange",
        "pepper",
        "lentils",
        "chutney",
    ],
}


def words_for(category: str | None) -> list[str]:
    """Return the words of a category, or every word when the category is unknown or empty."""
    if category and category.lower() in CATEGORIES:
        return CATEGORIES[category.lower()]
    return WORDS


def load_words(path: str) -> list[str]:
    """Read one word per line, keeping only lowercase alphabetic words.

    Blank lines and words with digits or symbols are skipped.
    """
    words = []
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            word = line.strip().lower()
            if word.isalpha():
                words.append(word)
    return words
